### ISSUE TITLE
https://www.facebook.com/profile.php?id=100093049797089&mibextid=opq0tG

### ISSUE THREAD

**Issue by Maricarmenpl** [scribblemaniac/facebook-tor-browser-search-plugin#1]
https://github.com/scribblemaniac/facebook-tor-browser-search-plugin/blob/d3c8ec67958f55ab17be3cf120d22aa3d6248a9e/facebookhs.xml#L10

**Comment by scribblemaniac** [comment]
I have updated this project. If you are still having issues, please describe them in detail, with words. If you keep making meaningless PRs, comments, and changes, I will treat this activity as spam.
